#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch=$(git branch | grep '*' | sed 's/* //')

if [[ "$branch" =~ ^(master|main|hotfix|develop)|(feat|chore|fix)\/[a-zA-z\d]+(\-[a-zA-Z\d]+)*$ ]]
then
  exit 0
else
  echo "Branch name is invalid" && exit 1
fi
