#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branchName=$(git branch | grep '*' | sed 's/* //')

if [ $branchName == 'master' ] || [ $branchName == 'main' ]
then
  echo -e "Commiting directly to the master/main branch is not permitted." && exit 1
fi

npm run lint && npm test -- --watchAll=false
