#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch=$(git branch | grep '*' | sed 's/* //')
branchRegex='(master|main|hotfix|develop)|(feat|chore|fix)\/[a-zA-z\d]+(\-[a-zA-Z\d]+)*'

if [[ $branch =~ $branchRegex ]]
then
  exit 0
else
  echo "Branch name is invalid" && exit 1
fi
