#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch=$(git branch | grep '*' | sed 's/* //')

if [ $branch == 'master' ] || [ $branch == 'main' ]
then
  echo -e "Commiting directly to the master/main branch is not permitted." && exit 1
fi

eslint --fix . && exit 0
