#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branchName=$(git branch | grep '*' | sed 's/* //')
branchRegex='^(master|main|hotfix|develop)|((feat|chore|fix|ci)/[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*)$'

if [[ $branchName =~ $branchRegex ]]; then
  exit 0
else
  echo "Branch name is invalid." && exit 1
fi
