name: Cypress e2e Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install --ignore-scripts

      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install Cypress Binary
        run: npx cypress install

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        env:
          TS_NODE_PROJECT: cypress/tsconfig.json
          TS_NODE_TRANSPILE_ONLY: "1"
        with:
          install: false
          config-file: cypress.config.js
          build: npm run build
          start: npm start
          browser: chrome
